const CATEGORIES_KEY = "categories";
const SETTINGS_KEY = "settings";
const UPDATES_KEY = "updates";
const DEFAULT_SETTINGS = { heroText: "Your anime-inspired hub for courses, study resources and daily progress.", aboutText: "Venom Study is a learning platform created to help you grow your skills through courses, resources and updates.", backgroundImage: "", appTitle: "Venom Study" };
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=UTF-8","cache-control":"no-store"}})}
function authorized(request,env){const supplied=request.headers.get("X-Admin-Password");return Boolean(env.ADMIN_PASSWORD&&supplied&&supplied===env.ADMIN_PASSWORD)}
async function getJSON(env,key,fallback){try{const raw=await env.CATEGORIES.get(key);if(!raw)return fallback;const data=JSON.parse(raw);return data??fallback}catch{return fallback}}
async function getCategories(env){const d=await getJSON(env,CATEGORIES_KEY,[]);return Array.isArray(d)?d:[]}
async function getSettings(env){const old=await getJSON(env,SETTINGS_KEY,{});return {...DEFAULT_SETTINGS,...(old&&typeof old==="object"?old:{})}}
function cleanCategory(input){return {id:String(input.id||crypto.randomUUID()),name:String(input.name||"").trim().slice(0,100),icon:String(input.icon||"📚").trim().slice(0,12),logo:String(input.logo||"").trim().slice(0,2000),url:String(input.url||"").trim().slice(0,2000),description:String(input.description||"").trim().slice(0,500)}}
function cleanUpdate(input){return {id:String(input.id||crypto.randomUUID()),type:String(input.type||"UPDATE").trim().slice(0,40),title:String(input.title||"").trim().slice(0,140),text:String(input.text||"").trim().slice(0,3000),image:String(input.image||"").trim().slice(0,2000),link:String(input.link||"").trim().slice(0,2000),createdAt:String(input.createdAt||new Date().toISOString())}}
export default {async fetch(request,env){const url=new URL(request.url);try{
 if(request.method==="GET"&&url.pathname==="/api/admin/check")return authorized(request,env)?json({ok:true}):json({error:"Unauthorized"},401);
 if(request.method==="GET"&&url.pathname==="/api/categories")return json(await getCategories(env));
 if(request.method==="PUT"&&url.pathname==="/api/categories"){if(!authorized(request,env))return json({error:"Unauthorized"},401);let input;try{input=await request.json()}catch{return json({error:"Invalid JSON."},400)}const category=cleanCategory(input||{});if(!category.name||!category.url)return json({error:"Category name and course URL are required."},400);const categories=await getCategories(env);const i=categories.findIndex(c=>String(c.id)===category.id);if(i>=0)categories[i]=category;else categories.push(category);await env.CATEGORIES.put(CATEGORIES_KEY,JSON.stringify(categories));return json({ok:true,category,categories})}
 if(request.method==="DELETE"&&url.pathname==="/api/categories"){if(!authorized(request,env))return json({error:"Unauthorized"},401);const id=url.searchParams.get("id");if(!id)return json({error:"Missing category id."},400);const categories=await getCategories(env);const updated=categories.filter(c=>String(c.id)!==String(id));await env.CATEGORIES.put(CATEGORIES_KEY,JSON.stringify(updated));return json({ok:true,categories:updated})}
 if(request.method==="GET"&&url.pathname==="/api/settings")return json(await getSettings(env));
 if(request.method==="POST"&&url.pathname==="/api/settings"){if(!authorized(request,env))return json({error:"Unauthorized"},401);let incoming;try{incoming=await request.json()}catch{return json({error:"Invalid JSON."},400)}const previous=await getSettings(env);const next={...previous,heroText:String(incoming.heroText??previous.heroText).trim().slice(0,600),aboutText:String(incoming.aboutText??previous.aboutText).trim().slice(0,1200),backgroundImage:String(incoming.backgroundImage??previous.backgroundImage).trim().slice(0,2000),appTitle:String(incoming.appTitle??previous.appTitle).trim().slice(0,100)};await env.CATEGORIES.put(SETTINGS_KEY,JSON.stringify(next));return json({ok:true,settings:next})}
 if(request.method==="GET"&&url.pathname==="/api/updates"){const items=await getJSON(env,UPDATES_KEY,[]);return json(Array.isArray(items)?items:[])}
 if(url.pathname==="/api/updates"&&request.method==="POST"){if(!authorized(request,env))return json({error:"Unauthorized"},401);let input;try{input=await request.json()}catch{return json({error:"Invalid JSON."},400)}const item=cleanUpdate(input||{});if(!item.title||!item.text)return json({error:"Update title and text are required."},400);const items=await getJSON(env,UPDATES_KEY,[]);const i=items.findIndex(x=>String(x.id)===item.id);if(i>=0)items[i]=item;else items.push(item);await env.CATEGORIES.put(UPDATES_KEY,JSON.stringify(items));return json({ok:true,updates:items,update:item})}
 if(url.pathname==="/api/updates"&&request.method==="DELETE"){if(!authorized(request,env))return json({error:"Unauthorized"},401);const id=url.searchParams.get("id");const items=await getJSON(env,UPDATES_KEY,[]);const next=items.filter(x=>String(x.id)!==String(id));await env.CATEGORIES.put(UPDATES_KEY,JSON.stringify(next));return json({ok:true,updates:next})}
 }catch{return json({error:"Server error."},500)}return env.ASSETS.fetch(request)}};
